#platform: darksky
#name: "Weather forecast"
#api_key: test
#update_interval:
#  minutes: 10
#monitored_conditions:
#  - summary
#  - hourly_summary
#  - temperature
#  - temperature_max
#  - temperature_min
