version: "3.7"
services:

  snips-satellite:
    container_name: snips-satellite
    build:
      context: ./snips-satellite
      dockerfile: Dockerfile.armhf
    privileged: true
    devices:
      - "/dev/snd"
    external_links:
      - mosquitto:mqtt
      - central-tts:central-tts
    networks:
      - smart-home-network
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /etc/machine-id:/etc/machine-id
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - ../common/snips-base/common-config/:/common-config

networks:
  smart-home-network:
    external: true