version: "3"
services:

  snips-sam:
    container_name: snips-sam
    build: ./snips-sam
    networks:
      - smart-home-network
    volumes:
      - ../common/snips-base/common-config/:/common-config

  snips-custom-word:
    container_name: snips-custom-word
    build: ./snips-custom-word
    privileged: true
    networks:
      - smart-home-network
    devices:
      - "/dev/snd"
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /etc/machine-id:/etc/machine-id
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - /snips-custom-word/hotword:/hotword

networks:
  smart-home-network:
    external: true