[snips-common]
bus = "mqtt"
mqtt = "mqtt:1883"
audio = ["satellite-development@mqtt"]
assistant = "/common-config/assistant"
user_dir = "/common-config/snips"

[snips-audio-server]
bind = "satellite-development@mqtt"

[snips-hotword]
model = "/common-config/hotword/sarah"
sensitivity = "0.5"
audio = ["satellite-development@mqtt"]

[snips-tts]
provider = "customtts"
customtts = { command = ["/files/voice.sh", "%%TEXT%%", "%%OUTPUT_FILE%%"] }