# light.development_ambient_light
platform: mqtt
name: "Development: Ambient Light"
state_topic: "stat/DVES_B46630/POWER"
command_topic: "cmnd/DVES_B46630/POWER"
availability_topic: "tele/DVES_B46630/LWT"

brightness_command_topic: "cmnd/DVES_B46630/DIMMER"
brightness_state_topic: "stat/DVES_B46630/RESULT"
brightness_value_template: "{{value_json.Dimmer}}"
brightness_scale: 100

rgb_command_template: "{{ '%02x%02x%02x00' | format(red, green, blue) }}"
rgb_command_topic: cmnd/DVES_B46630/Color
rgb_state_topic: "stat/DVES_B46630/RESULT"
rgb_value_template: "{{(value_json.Channel[0]*2.55)|int}},{{(value_json.Channel[1]*2.55)|int}},{{(value_json.Channel[2]*2.55)|int}}"

color_temp_command_topic: "cmnd/DVES_B46630/RESULT/CT"
color_temp_state_topic: "stat/DVES_B46630/RESULT"
color_temp_value_template: "{{value_json.CT}}"

white_value_state_topic: "stat/DVES_B46630/RESULT"
white_value_command_topic: "cmnd/DVES_B46630/Channel4"
white_value_scale: 100
white_value_template: "{{ value_json.Channel[3] }}"

qos: 1
payload_on: "ON"
payload_off: "OFF"
payload_available: "Online"
payload_not_available: "Offline"
retain: false
transition: 1