platform: mqtt
name: "Development: Light switch"
entity_id: "light.development.main_light"
state_topic: "stat/DVES_B46629/POWER"
command_topic: "cmnd/DVES_B46629/POWER"
availability_topic: "tele/DVES_B46629/LWT"
qos: 1
payload_on: "ON"
payload_off: "OFF"
payload_available: "Online"
payload_not_available: "Offline"
retain: false